"""Create jobs and job_attempts tables

Revision ID: bf16d475fd67
Revises: 
Create Date: 2026-09-05 23:58:31.073953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf16d475fd67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH')", name='ck_jobs_priority'),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_next_attempt_at', 'jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_jobs_status_priority_created_at', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING', 'COMPLETED', 'FAILED', 'RETRYING')", name='ck_job_attempts_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_attempts_job_id', 'job_attempts', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_attempts_job_id', table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index('ix_jobs_status_priority_created_at', table_name='jobs')
    op.drop_index('ix_jobs_status_next_attempt_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
